#!/bin/sh

# general script to start a browser

type=graphical
pipe=false
URL=http://luc42.lima-city.de
# elinks w3m links lynx
text_browser=elinks
# firefox dwb luakit jumanji surf uzbl
graphical_browser=firefox
quick_browser=luakit

firefox_half_quiet () {
  # pipe stderr of firefox into this, it's an open bug:
  # https://bugzil.la/833117
  sed -e "1{/^ *$/d;}" \
    -e "2{/(process:[0-9]*): GLib-CRITICAL \*\*: g_slice_set_config: assertion 'sys_page_size == 0' failed/d;}"
}
firefox_profiles () {
  # TODO
  local firefox_unix_ini="$HOME/.mozilla/firefox/profiles.ini"
  grep '^Name=' "$ini" | cut -f 2 -d =
}
firefox_open_profile () {
  local porfile
  for profile in `profiles`; do
    if [ "$profile" = "$1" ]; then
      # TODO
      exec open -na Firefox --args -P "$profile" -no-remote
    fi
  done
  echo $1 is not a valid profile. Try one of `profiles`.
  exit 2
}

text () {
  if [ -t 1 -o -t 2 ]; then
    exec "$text_browser" "$@"
  else
    exec term -e "$text_browser" "$@"
  fi
}

graphical () {
  if pgrep "$graphical_browser" >/dev/null; then
    exec "$graphical_browser" "$@"
  else
    exec "$quick_browser" "$@"
  fi
}

while getopts hgtp opt; do
  case $opt in
    h) help;;
    g) type=graphical;;
    t) type=text;;
    p) pipe=true;;
  esac
done
shift $((OPTIND-1))

if [ $# -eq 1 -a "$1" = - ]; then
  shift
  pipe=true
fi

if $pipe; then
  # save stdin to a file
  file=`mktemp -t tmp-$$-XXXXXX` || exit 1
  cat > "$file"                  || exit 1
  case `file --brief --mime-type "$file"` in
    text/html)
      mv "$file" "$file.html"
      file="$file.html"
      ;;
  esac
  $type "$file"
else
  $type "$@"
fi
