#!/bin/sh

tmp=`mktemp --tmpdir XXXXXX.html`

cat > $tmp <<EOF
<!DOCTYPE HTML>
<html>
<head>
<style>
max-width:100%;
max-height:100%;
</style>
</head>
<body>
<img src="$PWD/$1" align="center" />
</body>
</html>
EOF

w3m $tmp
rm -f $tmp
