#!/bin/sh

ini=$HOME/Library/Application\ Support/Firefox/profiles.ini
firefox=/Applications/Firefox.app/Contents/MacOS/firefox-bin

profiles () {
  grep '^Name=' "$ini" | cut -f 2 -d =
}

if [ $# -ne 1 ]; then
  echo Please give a profile.
  exit 2
fi

for profile in `profiles`; do
  if [ "$profile" = "$1" ]; then
    exec open -na Firefox --args -P "$profile" -no-remote
  fi
done

echo $1 is not a valid profile. Try one of `profiles`.
exit 2
