#!/usr/bin/env bash

if [[ "$1" = -h || "$1" = --help ]]; then
  echo "Usage: ${0##*/} [position]" >&2
  exit
fi

# preferred order of monitors (highest to lowest priority)
order=(eDP LVDS DP HDMI VGA)
# preferred position of monitors (relative to previous monitor in $order); we
# use the positional arguments for this because they are easier to shift
if [[ $# -eq 0 ]]; then
  set above right
fi
# maximum number of monitors to use (only names from $order will be used)
max=10

connected=($(xrandr | grep ' connected ' | cut -f 1 -d ' '))
options=()

for choice in ${order[@]}; do
  # iterate over the indices of the connected monitors
  for monitor in ${!connected[@]}; do
    if [[ ${connected[$monitor]} =~ $choice ]]; then
      if [[ ${#options[@]} -eq 0 ]]; then
	# set first match from $order as primary monitor
	options=(--output ${connected[$monitor]} --auto --primary)
      else
	# put monitor in $position of the $last one
	options=(${options[@]} --output ${connected[$monitor]} --auto --$1 $last)
	# shift to the next position unless we reached the last position
	if [[ $# -gt 1 ]]; then shift; fi
      fi
      # remember this monitor to position the next one
      last=${connected[$monitor]}
      # delete this monitor from the list of connected monitors
      unset connected[$monitor]
      connected=(${connected[@]})
      # count down the number of monitors that is desired at most
      ((max--))
      if [[ $max -eq 0 ]]; then
	break 2
      else
	break
      fi
    fi
  done
done

# let xrandr turn all disconnected monitors off (just in case) and also all
# connected monitors that where above the maximum number of desired monitors
for disconnected in $(xrandr | grep disconnected | cut -f 1 -d ' ') ${connected[@]}; do
  options=(${options[@]} --output $disconnected --off)
done

xrandr ${options[@]}
