#!/bin/sh

# try to connect to the wrong wlan in order to force netctl-auto to reconnect
# test if we can ping localhost
info_v () { echo Info: "$@" >&2; }
die_v () { echo Error: "$@" >&2; exit 1; }
info () { info_v "$@"; }
die () { die_v "$@"; }

test_only=false
force=false
service=netctl-auto@wlan0.service

connection () {
  if timeout 1s ping -c 1 -W 1 -q localhost >/dev/null; then
    # test if we can ping google
    if timeout 1s ping -c 1 -W 1 -q google.com >/dev/null; then
      info You seem to have internet connection.
      return 0
    else
      return 1
    fi
  else
    die Can not ping localhost.
    exit 1
  fi
}

if [ `id -u` -ne 0 ]; then
  export SUDO_ASKPASS=/usr/lib/ssh/ssh-askpass
  sudo=sudo
fi

while getopts ifkqtvx FLAG; do
  case $FLAG in
    t) test_only=true;;
    f) exec $sudo systemctl restart $service;;
    k) exec $sudo systemctl stop $service;;
    i) exec systemctl --no-pager status $service;;
    q) info () { true; }; die () { exit 1; };;
    v) info () { info_v "$@"; }; die () { die_v "$@"; };;
    x) set -x;;
  esac
done

if ! connection; then
  if $test_only; then
    info "You don't have internet connection."
    exit 1
  else
    info Reconecting to the network ...
    $sudo systemctl restart $service
  fi
fi
