#!/bin/sh

# try to connect to the wrong wlan in order to force netctl-auto to reconnect
# test if we can ping localhost
info_v () { echo Info: "$@" >&2; }
die_v () { echo Error: "$@" >&2; exit 1; }
info () { info_v "$@"; }
die () { die_v "$@"; }

test_only=false
force=false

connection () {
  if timeout 1s ping -c 1 -W 1 -q localhost >/dev/null; then
    # test if we can ping google
    if timeout 1s ping -c 1 -W 1 -q google.com >/dev/null; then
      info You seem to have internet connection.
      return 0
    else
      return 1
    fi
  else
    die Can not ping localhost.
    exit 1
  fi
}

while getopts tfqvx FLAG; do
  case $FLAG in
    t) test_only=true;;
    f) force=true;;
    q) info () { true; }; die () { exit 1; };;
    v) info () { info_v "$@"; }; die () { die_v "$@"; };;
    x) set -x;;
  esac
done

if $test_only; then
  if ! connection; then
    info "You don't have internet connection."
    exit 1
  else
    exit 0
  fi
fi

if $force || ! connection; then
  info Reconecting to the network ...
  if [ `id -u` -ne 0 ]; then
    export SUDO_ASKPASS=/usr/lib/ssh/ssh-askpass
    sudo=sudo
  fi
  $sudo systemctl restart netctl-auto@wlan0.service
fi
